name: My Custom Action
description: This is a custom action


runs:
  using: "composite"
  steps:
    - name: Upload JaCoCo coverage report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: build/JacocoReports/test/html

    - name: Upload test report
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: build/reports/tests/test
