name: My Custom Action
description: This is a custom action


runs:
  using: "composite"
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build and Run Tests with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3.0.2
      if: always() # always run even if the previous step fails
      with:
        report_paths: build/test-results/test/TEST-*.xml
