# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

#on:
#  release:
#    types: [created]
on:
  push:
    branches: [ feature/continous-integration-CI ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/MyAction
    - uses: ./.github/actions/BuildAction
    - uses: ./.github/actions/JacocoBadge
    - uses: ./.github/actions/TestAndCoverageReportAction


    - name: Step 3 - Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: build/libs/currency-rate-converter-0.0.1-SNAPSHOT.jar
