# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

#on:
#  release:
#    types: [created]
on:
  push:
    branches: [ feature/continous-integration-CI ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build and Run Tests with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build

    # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
    # the publishing section of your build.gradle
#    - name: Publish to GitHub Packages
#      uses: gradle/gradle-build-action@v2
#      with:
#        arguments: bootJar
#      env:
#        USERNAME: ${{ github.actor }}
#        TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: echo
      run: echo ${{ github.token }}

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3.0.2
      if: always() # always run even if the previous step fails
      with:
        report_paths: build/test-results/test/TEST-*.xml

    - name: Generate JaCoCo Badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-branches-badge: true
        jacoco-csv-file: build/JacocoReports/test/jacocoTestReport.csv
    - name: Log coverage percentage
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
        echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

    - name: Commit the badge (if it changed)
      run: |
        if [[ `git status --porcelain` ]]; then
          git config --global user.name 'evatikiotis'
          git config --global user.email '31160413@users.noreply.github.com'
          git add -A
          git commit -m "Autogenerated JaCoCo coverage badge"
          git push
        fi

    - name: Upload JaCoCo coverage report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: build/JacocoReports/test/html

    - name: Upload test report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: build/reports/tests/test

    - name: Step 3 - Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: build/libs/currency-rate-converter-0.0.1-SNAPSHOT.jar
